version: '3.8'

services:
  # The Cypress E2E testing service
  cypress-e2e:
    build:
      context: .
      dockerfile: etc/docker/cypress/Dockerfile
    networks:
      - nextapp-network
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_SCREENSHOT_ON_RUN_FAILURE=false
    volumes:
      - $PWD/cypress:/app/cypress:ro
      - $PWD/pages:/app/pages:ro
      - $PWD/public:/app/public:ro
      - $PWD/styles:/app/styles:ro
  # The Cypress components testing service
  cypress-components:
    build:
      context: .
      dockerfile: etc/docker/cypress/Dockerfile
    networks:
      - nextapp-network
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_SCREENSHOT_ON_RUN_FAILURE=false
    volumes:
      - $PWD/cypress:/app/cypress:ro
      - $PWD/pages:/app/pages:ro
      - $PWD/public:/app/public:ro
      - $PWD/styles:/app/styles:ro
    entrypoint: /app/entrypoint-components.sh
  # Run the next JS application in dev mode
  dev:
    image: node:18-alpine
    networks:
      - nextapp-network
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - $PWD/node_modules:/app/node_modules
      - $PWD/pages:/app/pages:ro
      - $PWD/public:/app/public:ro
      - $PWD/styles:/app/styles:ro
      - $PWD/next-env.d.ts:/app/next-env.d.ts:ro
      - $PWD/package.json:/app/package.json:ro
      - $PWD/tsconfig.json:/app/tsconfig.json:ro
      - $PWD/yarn.lock:/app/yarn.lock:ro
    command: sh -c "yarn && yarn dev"

networks:
  nextapp-network: